### ISSUE TITLE
Drop rates > 100%

### ISSUE THREAD

**Issue by Salvoxia** [molbal/abyss-tracker#10]
Hi, 

I noticed for the Triglavian Survey Database there's a drop rate > 100%
https://abyss.eve-nt.uk/loot/item/48121

I guess this only occurs with that item because it's the only item to really drop in every run.
I imagine other items might be off as well, but you wouldn't notice it. Perhaps there's a problem with the drop rate calculation when a run is deleted?

Best Regards,
Salvoxia

**Comment by molbal** [comment]
Hi,

Oh damnit. Yes, probably it is with the deletions.
The way the system works now is that it keeps how much runs were for every weather/difficulty combination and keeps how much of an item dropped. Then the next day it recalculates the run counts and adds the previous drop number to the new ones. Indeed, there is no subtraction anywhere, because the drop rate calculation does not check the previous runs..

I'll just apply a quick fix for now to hide the data inconsistency and do a proper fix after the fittings and some other requested features are added

**Comment by molbal** [comment]
Hi,

From now on deletions will affect the daily stats calculation. A full drop rate recalculation is running at the moment to get our stats right.

Best regards,
Balint
