### ISSUE TITLE
Idea: Record abyss run times using ESI location

### ISSUE THREAD

**Issue by Salvoxia** [molbal/abyss-tracker#2]
Hi,

I read about the idea of tracking the duration for each run on Reddit. I think it would be cool to use the ESI location endpoint toautomatically detect the start and end timestamp for an abyssal run. The solar system IDs for abyssal systems can be recognized easily.
When adding a run, the site could start polling the logged in character's location (cache timer is 5 seconds) and record the timestamp when the location switches to an abyssal system and when it switches back.

This could also be used to automatically determine the ship type.

Best Regards,
Salvoxia

**Comment by molbal** [comment]
Hello,

Yeah, it is possible. When its developed we will need to address a few points:

- Make it optional, lots of people are uncomfortable providing location information when they are flying bling ships
- Make it limited in time and not always running (The server doing lots of requests every time will be expensive both in CPU/network load and AWS bill)

Let's keep this issue open because it is a good idea

Best Regards,
Veetor

**Comment by Salvoxia** [comment]
I totally agree with you in both points.
It should absolutely be optional.
I envisioned something like a "start tracking" button on the "Add run" page that could run for a maximum of 30 minutes and try to detect start and end times.
If the user doesn't want to use automatic tracking, they could use two other buttons two manually fill the start and end time with the current timestamp.

Best Regards,
Salvoxia

**Comment by molbal** [comment]
That's a great idea it's something what I had in mind too.

A bit more dev will be needed, because this way a separation of the standard login and esin access scoped login will be needed. + Until now there were no real login system apart from an encrypted session cookie and a server side cache entry in Redis.

But since a profile page is already planned the functions will be done together. If everything goes according to plan I'll have time for it during the weekend :)


On Feb 7, 2020 18:02, Salvoxia <notifications@github.com> wrote:

I totally agree with you in both points.
It should absolutely be optional.
I envisioned something like a "start tracking" button on the "Add run" page that could run for a maximum of 30 minutes and try to detect start and end times.
If the user doesn't want to use automatic tracking, they could use two other buttons two manually fill the start and end time with the current timestamp.

Best Regards,
Salvoxia

**Comment by molbal** [comment]
Version 1.3, published today, has this implemented

**Comment by Salvoxia** [comment]
Great to hear!
I just checked it out. It said the stopwatch is enabled on my account, but when I started it and entered the abyss, it didn't pick up the time but continued to wait for me to enter it.
I also don't think I was asked for the ESI scopes required for location tracking when I logged in...

**Comment by molbal** [comment]
Thanks for checking it! You found a bug, it should only appear when you have authenticated the new scopes. Let me fix

**Comment by molbal** [comment]
It was an oversight on my part on how the DB handles empty fields. Fixed now!

**Comment by Salvoxia** [comment]
I tried again, it's now working as expected. Thank you so much for this great feature!

Two little suggestions:
- make the "Finished" label after returning to normal space green instead of red
- Does it fit with your design to automatically start the stopwatch if the permissions are there and the "Add run" page is opened? Would be one less click and easier to not forget ;)

**Comment by molbal** [comment]
Both done! :)

**Comment by Salvoxia** [comment]
Perfect, thanks!
