### ISSUE TITLE
Fitting stats: Drone Bay utilization not calculated correctly

### ISSUE THREAD

**Issue by Salvoxia** [molbal/abyss-tracker#24]
Hi,

I noticed that in the fitting states, the "used" value for the Drone Bay seems to be incorrect.

**Example 1:** https://abyss.eve-nt.uk/fit/85
Two different stacks of drones are listed for the Drone Bay, but only one of them seems to be taken into account for the volume calculation. And it's not the first stack.

**Example 2:** https://abyss.eve-nt.uk/fit/78
There is only a single stack of six medium drones, that should amount to 60 m³, but it only displays 20 m³ as "used".

Best Regards,
Salvoxia

**Comment by molbal** [comment]
Hey,

Its an unintentional side effect of a really ugly workaround. Since Pyfa does not split the drones (and probably won't do it: https://github.com/pyfa-org/Pyfa/issues/2186), I have to do it Abyss Tracker side. So this is why at line 100 here:  https://github.com/molbal/abyss-tracker/blob/master/app/Http/Controllers/EFT/FitHelper.php we have the pyfaBugWorkaround function that calculates Abyss Tracker side the drone bandwidth usage and after it is full, inserts a single tritanium (line 145) after them, forcing the other drones in the cargo.
This makes Pyfa return a wrong drone hold number.

I will sleep on a solution for this :) I can count the cargohold usage abyss tracker side, but I would rather keep all calculations in Pyfa

Best regards,
Veetor

**Comment by molbal** [comment]
Hey,

I went for the easy solution: drone bay hidden from GUI 
![we-smart](https://user-images.githubusercontent.com/5754480/82258902-f8e3b380-995a-11ea-9678-c6c8dbc212eb.gif)

Best regards,
Veetor
