### ISSUE TITLE
Display runs that used a specific fit (and maybe statistics for the fit)

### ISSUE THREAD

**Issue by Salvoxia** [molbal/abyss-tracker#28]
Hi,

on the "Fits" page, the fits seem to be ordered by the number of runs they have been used with. When displaying a fit, there's a link to the "ship" page, showing stats about that specific hull and all runs that hull was used in.
But there doesn't seem to be a way to show statistics for that specific fit, e.g. for run time evaluation.

Best Regards,
Salvoxia

**Comment by molbal** [comment]
Hi,

Yes, that is intentional for now. I plan to properly extend it and show performance for each fit and additional neat info like how many runs/time does it take on average for the fit to pay for itself.

However I wanted to do a minimum scope update first since and keep iterating because this update is by far the biggest of all so far both with added functionality and complexity.

Best regards,
veetor

**Comment by molbal** [comment]
This is WIP now - v1.5.1 has some advancements, but its not the final form :)

**Comment by molbal** [comment]
Hi @Salvoxia ,

![Képernyőkép 2020-09-12 – 21 07 43-fullpage](https://user-images.githubusercontent.com/5754480/93003094-10fbc600-f53c-11ea-8a3b-844848b457a6.png)

I can finally revisit this request of yours :) Next patch will have: similar fits, looting strategy and popularity like the in ship overview. Let me know if you need something else here

**Comment by molbal** [comment]
It is onlined - thanks for your patience
