### ISSUE TITLE
Consistent handling of loot/use of filament

### ISSUE THREAD

**Issue by msogrin** [molbal/abyss-tracker#3]
The app allows two modes of recording loot:
1. just paste the loot
2. paste both "before" and "after" loot

In the first case, the used filament is not recorded as "spent".
In the second case, it is recorded as "spent" and therefore is subtracted from the total loot. And if the same filament dropped, it's not recorded again.

In the end, these two methods return total loot which is different by the cost of the used filament.

I propose to automatically add 1 (or 3 for frigates) filament to "spent", and correctly show the loot even if the same filament was looted.

For cheaper filaments, that's not going to affect total loot much, but some there are some expensive ones (T5 exotic/electric/dark) which would severely skew the averages.

You might also want to retroactively subtract the spent filaments from old entries, which didn't have a filament recorded as spent. Otherwise, past statistics would be skewed again.

**Comment by molbal** [comment]
Hey,

Thanks for the ticket! Yes, this is indeed broken now. Until it is consistent, the spent items value is not withrawn from the loot sum. I will create a new field that will say "profit" and it will add the filaments for previous runs as well.

Until that is done I'll keep this issue open so you can be notified when its done

Cheers

**Comment by molbal** [comment]
Hello,

Since v1.3.4 the profit is visible and automatic additions are checked. For retaining data integrity these are calculated when a run is displayed. 

If you are interested in the exact calculation please check the normalizeLootAndLost function at the end of the AbyssController: https://github.com/molbal/abyss-tracker/blob/master/app/Http/Controllers/AbyssController.php

It does not apply correctly the 3 filaments for frigates yet, so I'm keeping this issue open for the time being

Cheers

**Comment by molbal** [comment]
Hey,

Today's unnamed bugfix release contained the fix for frigate filament prices. (This exact commit: https://github.com/molbal/abyss-tracker/commit/7e2d7ebd1da47aea6a56dbda92c615d560cc0c84)

Thanks again for the ticket! I'm closing it as I think there is nothing to do with it now.

BR
Veetor
