### ISSUE TITLE
Public fitting not showing up in Fits overview

### ISSUE THREAD

**Issue by Salvoxia** [molbal/abyss-tracker#33]
Hi,

this [public Sacrilege Fitting](https://abyss.eve-nt.uk/fit/158) (found in Fit Picker) is not showing up int the Fits overview.
It also has been saying "calculating stats" for over an hour at the time of posting this issue.

Best Regards,
Salvoxia

**Comment by molbal** [comment]
Hi,

Sometimes the AWS queue drops connection. In that case fits are stuck in calculating stats status until a scheduled task reconnects the queue every day. Let's see what the status is in 10 hours

**Comment by Salvoxia** [comment]
Does this mean that the fitting will show up on the "Fits" page when the calculations are done (i.e. the page only shows Fits with calculated stats)? Or is that a different problem?

**Comment by molbal** [comment]
Yes. For a fit to show up it needs two criteria accomplished:

- calculation status 'done' 
- privacy "Incognito" or "Public"

I'll see tomorrow morning if the issue is still there or not - but at least I'll do a better calculation message explaining this - or do an auto AWS queue reconnect if I see a fit that's stuch in 'queued' process status for too long

**Comment by molbal** [comment]
I updated the fit stat service's database to the 2020.05.28 version (https://github.com/molbal/Pyfa/commit/9e0561ad7e750eb7976b63cac949749251297876) and submitted all fits. No fits could be calculated in the last 4 days lets hope this solves it. There are also some issues with submissions due to the new module names.

**Comment by molbal** [comment]
I accidentally deployed a file to 1.5.1 from 1.5.2 and that broke the part of the site that receives fit stats from the external service. I'm ashamed, but the stats are visible for all submitted fits in the last 4 days
