### ISSUE TITLE
Filament added as loot when there is none looted

### ISSUE THREAD

**Issue by philippeop** [molbal/abyss-tracker#39]
**Filament appearing in the loot**
I post my before and after in a T4 and it says I looted a T4 filament

See https://abyss.eve-nt.uk/run/25056

**To Reproduce**
1. Add a new run
2. Set the run to T4 Exotic
3. Paste in the "before":
```
Agency 'Pyrolancea' DB5 Dose II	1
Mjolnir Fury Light Missile	972
Nanite Repair Paste	200
Scourge Fury Light Missile	3640
```

4. Paste in the after:
```
Mjolnir Fury Light Missile	972
Nanite Repair Paste	200
Scourge Fury Light Missile	3368
Triglavian Survey Database	145
Zero-Point Condensate	98
```
5. Submit the run
4. See the run looted/expended

**Expected behavior**
Gained Triglavian Survey Database, Zero-Point Condensate
Spent Raging Exotic Filament, Scourge Fury Light Missile, and Agency 'Pyrolancea' DB5 Dose II

**Current behavior**
Same as above, but Raging Exotic Filament appears gained

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 83.0.4103.97

**Comment by philippeop** [comment]
https://abyss.eve-nt.uk/run/25060

**Comment by molbal** [comment]
Hello,

This is the side effects of an intentional design choice.

The site expects a difference in the selected type/tier's filament count in the before/after run because obviously a run uses up a filament. 

So this automatically places one filament in the consumed part of the run, if there weren't any.

However after this it checkes if the before cargo space if the filament's count in the cargo is the same or not. 

In your case the before cargo and after cargo both shows the same amount (0) so the site thinks your looted a filament and immediately consumed it to get to the abyss.

***To fix this please include the filament too in the before cargo.***

I hope I could explain how this works
Cheers
