### ISSUE TITLE
Run shows no loot when submitting

### ISSUE THREAD

**Issue by Sonreir66** [molbal/abyss-tracker#81]
**Describe the bug**
When pasting the contents of my ship cargo into the run, the value of the contents is not calculated. Upon submission, the detail screen shows that I have no loot, which is incorrect.

**To Reproduce**
See biug description

**Expected behavior**
Loot value should be calculated and show in the details, rather than abandoned and showing no loot.

**Screenshots**
https://imgur.com/qPmxwfl

**Desktop (please complete the following information):**
Windows 10

**Smartphone (please complete the following information):**
N/A

**Additional context**

**Comment by molbal** [comment]
Hi Sonreir,

This is usually caused by https://www.eveworkbench.com/tools/appraisal behaving incorrectly - the current Abyss Tracker version (1.9) solely relies on Eve Workbench, but the upcoming patch (1.10, semi finished, delayed due to IRL) will add https://janice.e-351.com/ as another appraisal engine so we'll have a hot failover option.

**Comment by DrKalv** [comment]
In addition to Sonreir, sometimes I even get the correct loot values calculated in the run submission screen, but after submission it still says "no loot".

**Comment by molbal** [comment]
Fixed
